### ISSUE TITLE
Support for ramsey/uuid=^4.0

### ISSUE THREAD

**Issue by petski** [ekreative/uuid-extra-bundle#11]
In Feb/Mar 2020, `ramsey/uuid=^4.0` was released. Latest version of `mcfedr/uuid-extra-bundle` [1] requires `ramsey/uuid=^3.0`. Please support `ramsey/uuid=^4.0`

[1] P.S. according to https://github.com/mcfedr/uuid-extra-bundle/releases this 2.3.1, not 3.1.2

**Comment by mcfedr** [comment]
Fixed in 3.2
