### ISSUE TITLE
Support `sensio/framework-extra-bundle:^6`

### ISSUE THREAD

**Issue by Ocramius** [ekreative/uuid-extra-bundle#17]
This is mostly a placeholder, potentially fixed by @dependabot upgrades (see https://github.com/ekreative/uuid-extra-bundle/pull/16#pullrequestreview-837614577), but in:

https://github.com/ekreative/uuid-extra-bundle/blob/3744cf92a0bffa151e92a7dccb397d958f1c0ed5/composer.json#L10-L11

It would be a good idea to:

 * add `symfony/*:^6` support
 * drop `symfony/*:^3` and `symfony/*:^4` support (old versions still work, no?)

**Comment by mcfedr** [comment]
closed by https://github.com/ekreative/uuid-extra-bundle/pull/18
